[providers]
java = "19"

[phases.setup]
nixPkgs = ["openjdk19"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -jar target/beautybooking-0.0.1-SNAPSHOT.jar"